### PR TITLE
Feature: Sync latest content from fabric-bootcamp-chaincode

### PR DESCRIPTION
**Pull request by ThomasRalee**
## This PR:
- Syncs latest content from https://github.com/chainstack/fabric-bootcamp-chaincode

### CODE REVIEW

**Comment by CaJIbHuK** [comment]
@ThomasRalee shall I merge this?

**Review by akegaviar — CHANGES_REQUESTED** [review]
Looks like the chaincode upgrade script is missing.

**Comment by akegaviar** [comment]
@ThomasRalee @CaJIbHuK any chance we can speed this up? It's a public facing blog post that's in the top 3 in popularity.

**Comment by CaJIbHuK** [comment]
@ThomasRalee let's finalize the PR please

**Comment by ThomasRalee** [comment]
@akegaviar added the upgrade chaincode command to the `chaincode.sh base script`. Command is the same as stated on the [blog post](https://chainstack.com/deploy-a-hyperledger-fabric-v2-web-app-using-sdk-for-node-js/).
> `node webapp/server/cli/peer upgrade `

Screen Shot 2021-04-21 at 2 38 37 PM

**Comment by akegaviar** [comment]
@ThomasRalee the backend part isn't starting for me now:

```
ake@akes-MacBook-Pro server % npm run start

> fabricWebApp@1.0.0 start /Users/ake/freedom-dividend-chaincode/webapp/server
> babel-node ./app.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/core/lib/parser/index.js:95
    throw err;
    ^

SyntaxError: /Users/ake/freedom-dividend-chaincode/webapp/server/api/index.js: Identifier 'contract' has already been declared (90:10)

  88 |     const contract = await network.getContract(req.params.chaincode);
  89 |     const response = await contract.evaluateTransaction('org.hyperledger.fabric:GetMetadata').toString();
> 90 |     const contract = JSON.parse(response);
     |           ^
  91 | 
  92 |     res.send({
  93 |       mspId: envfile.parseFileSync(`${rootPath}/webapp/server/.env`).MSP_ID,
    at Parser._raise (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/parser/location.js:241:45)
    at Parser.raiseWithData (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/parser/location.js:236:17)
    at Parser.raise (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/parser/location.js:220:17)
    at ScopeHandler.checkRedeclarationInScope (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/util/scope.js:137:12)
    at ScopeHandler.declareName (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/util/scope.js:98:12)
    at Parser.checkLVal (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/parser/lval.js:392:22)
    at Parser.parseVarId (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/parser/statement.js:1029:10)
    at Parser.parseVar (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/parser/statement.js:996:12)
    at Parser.parseVarStatement (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/parser/statement.js:688:10)
    at Parser.parseStatementContent (/Users/ake/freedom-dividend-chaincode/webapp/server/node_modules/@babel/parser/src/parser/statement.js:209:21) {
  loc: Position { line: 90, column: 10 },
  pos: 3145,
  code: 'BABEL_PARSE_ERROR'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabricWebApp@1.0.0 start: `babel-node ./app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabricWebApp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ake/.npm/_logs/2021-04-21T07_38_21_137Z-debug.log
```

**Comment by ThomasRalee** [comment]
@akegaviar fixed the error, can you check it again?

**Comment by akegaviar** [comment]
@ThomasRalee I can now install and commit the chaincode, but cannot access it:

Fabric v2 1 web app 2021-04-23 15-47-25

**Comment by akegaviar** [comment]
@ThomasRalee I think the upgrade now installs the chaincode as a separate chaincode that you need to install and commit again?

I can't commit the the new chaincode again and also I get the red blank bar at the bottom.

```
ake@akes-MacBook-Pro cli % node peer upgrade
executing cli - upgrade command

2021-04-23 16:15:45.304 +08 [cli.lifecycle.chaincode] submitInstallProposal -> INFO 001 Installed remotely: response:<status:200 payload:"\n[freedomDividendContract1.1:1e42265415ea613961053b388521ebbbc856dca1048e2ca987ccb165ed80611c\022\032freedomDividendContract1.1" > 
2021-04-23 16:15:45.305 +08 [cli.lifecycle.chaincode] submitInstallProposal -> INFO 002 Chaincode code package identifier: freedomDividendContract1.1:1e42265415ea613961053b388521ebbbc856dca1048e2ca987ccb165ed80611c
```

Fabric v2 1 web app 2021-04-23 16-21-35

**Comment by ThomasRalee** [comment]
Hi @akegaviar,
I've updated the `/network` API endpoint to fetch only the active chaincode, there is a conflict of sequence number for different chaincodes. Tested the entire upgrade flow and everything works smoothly, please check again. Thanks!

**Comment by akegaviar** [comment]
@ThomasRalee here's what I get now when trying to access an upgraded chaincode:

Fabric v2 1 web app 2021-04-23 22-10-32

**Review by akegaviar — APPROVED** [review]
Looks like it's working now and in tune with the blog post on staging.

I will check with a fresh network later just in case.

**Pull request merged**
